### ISSUE TITLE
Eye Tracking API

### ISSUE THREAD

**Issue by Jack8Trades** [QLou895/Terrified_2.0#1]
### Eye Tracking APIs & Research

- [ ] Reasearch API to implement Eye Tracking in game
- [ ] Learn how to set up inside of Unity
- [ ] Use inside game
